### ISSUE TITLE
TODO: M1 Mac Tasks

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#2452]
- [ ] Add detailed instructions for M1 mac to the wiki here: https://www.pygame.org/wiki/MacCompile
- [x] find at least one contributor who has a shiny new M1 mac and is willing to test/troubleshoot the build system
- [ ] investigate up-to-dateness of SDL2 (and possibly pygame) in macports/fink/homebrew
- [ ] manually upload arm64 binary wheels for mac os 11
- [ ] better error messages when SDL2/sdl2-config is not installed/not found
- [ ] (optional) update build script for building with SDL2 Framework (instead of sdl2-config)
- [ ] maybe warn during build when an older SDL2 version is found
- [ ] investigate code paths and build flags for fast blitting on aarch64 (RPi4 and M1)
- [ ] have CI on mac OS again

related: https://github.com/libsdl-org/SDL/issues/4181

**Comment by Carlosted** [comment]
@robertpfeiffer I do have a new M1 mac and would love to help. I'm probably not the best for this job because I'm very new to programming and don't know a lot about git. If you ever need help testing things you can contact me. Also, english is not my first language and I still go to school so I might not answer quickly.

**Comment by johnson7788** [comment]
> Is there help available for getting pygame to work on M1s as this thread implies? My friend tried installing it, but it couldn't find pygame.mixer (and some other packages), which sounds like the issues that others have had with SDL2.

same issue, Mac M1

```
/Users/admin/git/rl-flappybird/src/flappy.py:156: RuntimeWarning: use mixer: No module named 'pygame.mixer'
(ModuleNotFoundError: No module named 'pygame.mixer')
  SOUNDS["die"] = pygame.mixer.Sound("data/assets/audio/die" + soundExt)
Traceback (most recent call last):
  File "/Users/admin/git/rl-flappybird/src/flappy.py", line 711, in <module>
    main()
  File "/Users/admin/git/rl-flappybird/src/flappy.py", line 156, in main
    SOUNDS["die"] = pygame.mixer.Sound("data/assets/audio/die" + soundExt)
  File "/Users/admin/miniforge3/envs/py38/lib/python3.8/site-packages/pygame/__init__.py", line 59, in __getattr__
    raise NotImplementedError(missing_msg)
NotImplementedError: mixer module not available (ModuleNotFoundError: No module named 'pygame.mixer')
```

**Comment by devinsuttles** [comment]
Any work arounds on getting pygame to work for arm chip Macs?

**Comment by mdiazv** [comment]
How can I help? :) I have a shiny M1 Mac and could spare a few hours if directed.

**Comment by robertpfeiffer** [comment]
> How can I help? :) I have a shiny M1 Mac and could spare a few hours if directed.

@mdiazv You could install SDL2 via homebrew or with the binary downloads from here: https://www.libsdl.org/download-2.0.php and try compiling pygame against either one.

If you make a detailed step-by-step guide about installing SDL2 and other dependencies (like libjpeg) on a fresh install, that would help a lot. You should probably use homebrew SDL2 with homebrew python, or everything from macports analogously. Getting everything to work with Python framework and SDL2 framework would also be cool, but that requires changing the build system. We haven't worked on the mac-only code paths in a while.

As for the "if directed", well, this first task is "write a tutorial and document the pitfalls", not "follow a tutorial to the letter".

**Comment by andrewdstrain** [comment]
I've got an M1 MacBook Air. After the fix in pull request #2508, `pygame.examples.aliens` works as expected (obviously, it didn't before the fix). However, `pygame. tests` still does not pass 100%. In particular, the following errors are found:

```
(venv) mac@MacBookAir pygame % python -m pygame.tests
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
skipping pygame.tests.cdrom_test (tag 'interactive')
skipping pygame.tests.overlay_test (tag 'SDL2_ignore')
skipping pygame.tests.scrap_test (tag 'SDL2_ignore')
skipping pygame.tests.sndarray_test (tag 'ignore')
skipping pygame.tests.surfarray_test (tag 'ignore')
loading pygame.tests.base_test
loading pygame.tests.blit_test
loading pygame.tests.bufferproxy_test
loading pygame.tests.camera_test
loading pygame.tests.color_test
loading pygame.tests.compat_test
loading pygame.tests.constants_test
loading pygame.tests.cursors_test
loading pygame.tests.display_test
loading pygame.tests.draw_test
loading pygame.tests.event_test
loading pygame.tests.fastevent_test
loading pygame.tests.font_test
loading pygame.tests.freetype_test
loading pygame.tests.ftfont_test
loading pygame.tests.gfxdraw_test
loading pygame.tests.image__save_gl_surface_test
loading pygame.tests.image_test
loading pygame.tests.imageext_test
loading pygame.tests.joystick_test
loading pygame.tests.key_test
loading pygame.tests.mask_test
loading pygame.tests.math_test
loading pygame.tests.midi_test
loading pygame.tests.mixer_music_test
loading pygame.tests.mixer_test
loading pygame.tests.mouse_test
loading pygame.tests.pixelarray_test
loading pygame.tests.pixelcopy_test
loading pygame.tests.rect_test
loading pygame.tests.rwobject_test
loading pygame.tests.sprite_test
loading pygame.tests.surface_test
loading pygame.tests.surflock_test
loading pygame.tests.sysfont_test
loading pygame.tests.threads_test
loading pygame.tests.time_test
loading pygame.tests.touch_test
loading pygame.tests.transform_test
loading pygame.tests.version_test
loading pygame.tests.video_test
......................................................................................................................................................s..s...............s.............................................................................................................................................................................................................................................................................................................................................s.............................................................................................................s.....s.............................................................................................................................................................xxxxxxx......x...........x........x.............................................x...x.............................................................................................................................................EEEEEEEE..s.........s..........s.s.....................................................................................................................................................................................................................................................................................................................................................................................................................................................s.s...............................................s......s......s...........................s.s......................s.s....................................s..
======================================================================
ERROR: test_MidiException (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MidiException is raised as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_conversions (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
of frequencies to midi note numbers and ansi note names.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midiin (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MIDIIN event id exists in the midi module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midiout (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MIDIOUT event id exists in the midi module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midis2events (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events are properly converted to pygame events.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midis2events__extra_event_data (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with extra values are handled properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midis2events__extra_event_data_missing_timestamp (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with extra data and no timestamps are handled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

======================================================================
ERROR: test_midis2events__missing_event_data (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with missing values are handled properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/geek/src/pygame/venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ModuleNotFoundError: No module named 'pygame.pypm'

----------------------------------------------------------------------
Ran 1633 tests in 38.378s

FAILED (errors=8)

(venv) mac@MacBookAir pygame % 
```

**Comment by andrewdstrain** [comment]
> * [ ]  Add detailed instructions for M1 mac to the wiki here: https://www.pygame.org/wiki/MacCompile

I'm willing to do this but it says that registration is disabled. Please advise.

**Comment by andrewdstrain** [comment]
From a clean slate (empty Homebrew): Run the following commands and it works:

```
brew update
brew install python@3.9
brew install pkg-config
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf

python3 -m venv venv
source ./venv/bin/activate

pip install --upgrade pip setuptools

pip install wheel
pip install venvdotapp
venvdotapp

pip install --no-cache-dir git+https://github.com/nelsonlove/pygame
```

Of course, that last line needs to be changed....but that's how I got it to work for now.

**Comment by mdiazv** [comment]
I confirm the above steps by @andrewdstrain work on my M1 Mac too!

**Comment by robertpfeiffer** [comment]
thanks, @andrewdstrain. I'll edit the wiki later today and link to this issue.

Can you clone/checkout https://github.com/nelsonlove/pygame and tell me if `python3 setup.py config -auto` finds optional dependencies like libjpeg and portmidi? Do they also have to be installed via homebrew?

That PR probably needs to be rebased and refactored.

Last time I looked into getting this to work with the SDL2 framework and Python framework, I gave up because this would actually require code changes, and it was x86-only anyway. We may want a different file from `config_darwin.py` for M1 mac buildconfig and just require SDL2 or higher. Maybe we could call it `config_macos11_arm.py`

**Comment by andrewdstrain** [comment]
@robertpfeiffer,

Yes, I'll do that. If it helps, below, are the versions of SDL2 that Homebrew is using:

As for libjpeg and portmidi, using the steps, above, does not incorporate them. But I'll check doing it the other way, above. I can do a comparison of the two ways and see if anything is added. I know I've already tried portmidi (due to the error in pygame.tests and, using the above method, didn't add it. But I'm going to do it exactly as you said.

```
sdl2       2.0.14_1
sdl2_gfx   1.0.4
sdl2_image 2.0.5
sdl2_mixer 2.0.4_1
sdl2_net   2.0.1
sdl2_ttf.  2.0.15
```

**Comment by andrewdstrain** [comment]
Here's the output of `python3 setup.py config -auto`:

```
Using Darwin configuration...

Hunting dependencies...
SDL     : found 2.0.14
FONT    : found
IMAGE   : found
MIXER   : found
Framework CoreMIDI not found
Framework QuickTime not found
PNG     : found
JPEG    : found
PORTMIDI: found
FREETYPE: found 23.4.17

If you get compiler errors during install, double-check
the compiler flags in the "Setup" file.


Continuing With "setup.py"
running config
```

Okay - so it seems that `portmidi` (libjpeg is already installed) needs to be added to my steps, above. However, an install did not fix `pygame.tests`.

**Comment by andrewdstrain** [comment]
@robertpfeiffer @mdiazv 

I finally figured out how to fix `pygame.tests` to work 100%. The reason it was failing is because Setup has the `pygm` module commented out but it was being tested for anyway. Here's how to get it to work, from the beginning:

```
brew update
brew install python@3.9
brew install pkg-config portmidi
brew install sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf

python3 -m venv pygame2
source ./pygame2/bin/activate

pip install --upgrade pip setuptools

pip install wheel
pip install venvdotapp
venvdotapp

git clone https://github.com/nelsonlove/pygame
cd pygame
python setup.py config -auto
```

From here, we need to edit the Setup file. In particular change

```
PORTTIME = -lC -lo -lr -le -lM -lI -lD -lI
```

to

```
PORTTIME = -lC -lM
```

and change

```
#pypm src_c/pypm.c $(SDL) $(PORTMIDI) $(PORTTIME) $(DEBUG)
```

to

```
pypm src_c/pypm.c $(SDL) $(PORTMIDI) $(PORTTIME) $(DEBUG)
```

Save the Setup file and, finally:

```
python setup.py install

python -m pygame.tests
```

And it will pass 100% of the tests.

Ideally, for those that don't want `pygm`, the default, the tests should not test for it and it will pass 100%. And, of course, test for it if it is enabled. But that's probably more work than is needed.

**Comment by andrewdstrain** [comment]
I discovered that having XQuartz installed increases performance. The `pygame.tests` are about 20 seconds faster just with it installed. You don't even have to use it.

**Note**: XQuartz is a Universal binary. Everything I've been doing is arm64 or Universal. No Intel, only, at all.

**Comment by gramss** [comment]
@andrewdstrain , I followed your exact steps, but I only get pixel "rubbish" out of the tests. As I have never sawn any tests successfully before I cannot confirm if they are intended that way..

But I would say not.
Could you verify that everything still works on your end?

Here is a picture I took from a test, to give some ideas about it:
![grafik](https://user-images.githubusercontent.com/6034322/131204227-9aefae4e-42be-4241-8268-fc36e3adac33.png)

They appear in saller and bigger ways. Here are the failures I got from the tests:

......................................................................................................................................................s..s...............s..............................................................................................................................................................................................................................................F................F.............................................................................s.............................................................................................................s.....s........F....................................................................................................................................................xxxxxxx......x...........x........x.............................................x...x.......................................................................................................................................................s.........s..........s.s.....................................................................................................................................................................................................................................................................................................................................................................................................................................................s.s...............................................s......s......s...........................s.s......................s.s....................................s..
======================================================================
FAIL: test_get_grab (pygame.tests.event_test.EventModuleTest)
Ensure get_grab() works as expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "............./pygame2/lib/python3.9/site-packages/pygame-2.0.2.dev1-py3.9-macosx-11-arm64.egg/pygame/tests/event_test.py", line 776, in test_get_grab
    self.assertEqual(pygame.event.get_grab(), i % 2)
AssertionError: 0 != 1

======================================================================
FAIL: test_set_grab__and_get_symmetric (pygame.tests.event_test.EventModuleTest)
Ensure event grabbing can be enabled and disabled.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "............./pygame2/lib/python3.9/site-packages/pygame-2.0.2.dev1-py3.9-macosx-11-arm64.egg/pygame/tests/event_test.py", line 697, in test_set_grab__and_get_symmetric
    self.assertTrue(pygame.event.get_grab())
AssertionError: 0 is not true

======================================================================
FAIL: test_get_focused (pygame.tests.key_test.KeyModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "............./pygame2/lib/python3.9/site-packages/pygame-2.0.2.dev1-py3.9-macosx-11-arm64.egg/pygame/tests/key_test.py", line 49, in test_get_focused
    self.assertTrue(focused)
AssertionError: 0 is not true

----------------------------------------------------------------------
Ran 1633 tests in 57.896s

FAILED (failures=3)

I hope it helps.. :) Still thank you for your effort!
Thanks to the line with the tests I know that I have an issue with pygame and not the application I wanna run. At least something.. 👍 

And yes, I run the exact same steps as you above.

**Comment by pkulev** [comment]
Guys, when release with M1 support will be available in PyPI? It's quite inconvinient to build all of this by hands...

**Comment by evprkr** [comment]
> Guys, when release with M1 support will be available in PyPI? It's quite inconvinient to build all of this by hands...

I'm also wondering this. Please give us a release!

**Comment by illume** [comment]
Anyone with an M1 able to test if the pre-release works for them on M1?
```
python3 -m pip install pygame==2.0.3.dev6
```

**Comment by solozobov** [comment]
For me it worked. Thank You!!!
<img width="1440" alt="Screenshot 2021-10-31 at 16 19 41" src="https://user-images.githubusercontent.com/2632376/139585529-217e983a-16df-42bd-86d2-80126c962934.png">
ed

**Comment by illume** [comment]
Thanks @solozobov 

I wonder if it runs ok?
```
# run an example game
python3 -m pygame.examples.aliens
# run the full test suite. (save your work first, takes a couple of minutes, goes fullscreen and back, makes noises)
python3 -m pygame.tests
```

**Comment by pkulev** [comment]
8 tests failed, other passed.

```
======================================================================
ERROR: test_MidiException (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MidiException is raised as expected.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_conversions (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
of frequencies to midi note numbers and ansi note names.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midiin (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MIDIIN event id exists in the midi module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midiout (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures the MIDIOUT event id exists in the midi module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midis2events (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events are properly converted to pygame events.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midis2events__extra_event_data (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with extra values are handled properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midis2events__extra_event_data_missing_timestamp (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with extra data and no timestamps are handled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

======================================================================
ERROR: test_midis2events__missing_event_data (pygame.tests.midi_test.MidiModuleNonInteractiveTest)
Ensures midi events with missing values are handled properly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/tests/midi_test.py", line 344, in setUp
    import pygame.midi
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/midi.py", line 35, in <module>
    import pygame.pypm as _pypm
ImportError: dlopen(/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so, 2): Symbol not found: _Pt_Time
  Referenced from: /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/pypm.cpython-39-darwin.so

----------------------------------------------------------------------
Ran 1678 tests in 50.941s

FAILED (errors=8)
```

**Comment by ankith26** [comment]
Thanks for testing reporting the issue! So `pygame.midi` is having some problems here on M1 mac chips! I will look into this now. Also in the meantime if you find any other issues while running pygame examples and such, do report it :)

**Comment by pkulev** [comment]
I've tested all the examples.
* As expected, **midi** example doesn't work with the same 'symbol not found' error.
* **music_drop_fade** looks a little weird:
<img width="752" alt="изображение" src="https://user-images.githubusercontent.com/1115916/139588388-eb4b7b6b-3fea-4d49-ac54-073e8acaf713.png">
* **scrap_clipboard** acts weird too:
<img width="312" alt="изображение" src="https://user-images.githubusercontent.com/1115916/139588638-ca886600-208f-40ee-a42e-d97b665e3c75.png">
half of commands cause errors:
```
Putting image into the clipboard.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/examples/scrap_clipboard.py", line 88, in <module>
    scrap.put("image/bmp", buf)
pygame.error: content could not be placed in clipboard.

Placing clipboard text.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/most/proj/astrolero/.venv/lib/python3.9/site-packages/pygame/examples/scrap_clipboard.py", line 72, in <module>
    scrap.put(pg.SCRAP_TEXT, as_bytes("Hello. This is a message from scrap."))
pygame.error: content could not be placed in clipboard.
```

**Comment by ankith26** [comment]
I opened #2808 to fix the midi issue on M1 macs. 

About the screen having noise, It is likely related to the SDL issue that happens on macs, where surfaces are not filled with black colour on creation. And scrap is partly broken on mac anyways, it was never considered "stable".

These issues should be fixed at some point, but are not blockers for the upcoming release :)

**Comment by ankith26** [comment]
Now pygame works fine on apple silicon, so this issue can be closed. Yet there are some tasks in the original comment that are nice to have, and are not M1 specific so they should be in their own issue to be addressed

> better error messages when SDL2/sdl2-config is not installed/not found
> (optional) update build script for building with SDL2 Framework (instead of sdl2-config)
> maybe warn during build when an older SDL2 version is found
