### ISSUE TITLE
Add Keyword Arguments to event.c, display.c, color.c, font.c, and rect.c

### ISSUE THREAD

**Issue by jonotassia** [pygame/pygame#3852]
Creating a new issue to track adding kwargs to the functions (per #808) below. 

**Approach**:
- Create a pull request for each function and make the following changes to each:
    - Update function
    - Update stubs
    - Update docs
    - Update test case

**Event.c**

- [x] `event_name` - #3854 

**Display.c**

- [x] `pg_gl_set_attribute` - #3859 
- [x] `pg_gl_get_attribute` - #3859 
- [x] `pg_set_palette` - #3859 
- [x] `pg_set_gamma` - Deprecated, did not update
- [x] `pg_set_gamma_ramp` - Deprecated, did not update
- [x] `pg_set_caption` - #3859 

**Color.c**

- [x] `_color_correct_gamma` - #3858 
- [x] `_color_set_length` - Deprecated, did not update

**Font.c**

- No changes made - The only function that appears to take args is get_ttf_version, which is already accounted for

**Rect.c**

- Will modify
   
    - [x]  `pg_rect_clipline` - #3872
    - [x]  `pg_rect_scale_by` - #3872
    - [x]  `pg_rect_scale_by_ip` - #3872
    - [x]  `pg_rect_unionall` - #3872
    - [x]  `pg_rect_unionall_ip` - #3872
    - [x]  `pg_rect_collidelist` - #3872
    - [x]  `pg_rect_collidelistall` - #3872
    - [x]  `pg_rect_collidedict` - #3872
    - [x]  `pg_rect_collidedictall` - #3872

- Will not modify since it calls pgRect_FromObject rather than PyArg_ParseTupleAndKeywords
    - `pg_rect_clip`
    - `pg_rect_clamp`
    - `pg_rect_fit`
    - `pg_rect_clamp_ip`
    - `pg_rect_update`
    - `pg_rect_union`
    - `pg_rect_union_ip`
    - `pg_rect_colliderect`
    - `_pg_rect_contains`
- Will not modify since it calls pg_TwoIntsFromObj rather than PyArg_ParseTupleAndKeywords
    - `pg_rect_move`
    - `pg_rect_move_ip`
    - `pg_rect_inflate`
    - `pg_rect_inflate_ip`
    - `pg_rect_collidepoint`

**Comment by jonotassia** [comment]
All in-scope changes made. Closing issue.
