### ISSUE TITLE
pygame 1.9.4 release

### ISSUE THREAD

**Issue by illume** [pygame/pygame#390]
Please leave a comment if you have done some testing, and what you tested.

- [x] go through the issue tracker, and pull requests to include as much as we can.
- [x] announce intention to release on mailing list.
- [x] look at [distro bug trackers](http://www.pygame.org/wiki/patchesandbugs#OS/Distribution%20bug%20trackers%20for%20pygame) for bugs, and patches (debian, fedora, etc).
  - [x] address debian issues
  - [x] look through ubuntu issues
  - [x] [fedora issues](https://bugz.fedoraproject.org/pygame)
- [x] docs are building and ok.
- [x] make raspberry wheels: https://github.com/bennuttall/piwheels/issues/52
- [x] ~~high cpu sound issue~~ issue identified, reported upstream https://github.com/pygame/pygame/issues/331
- [ ] timidity config paths issue https://github.com/pygame/pygame/issues/343
- [x] Two [source alpha](https://bitbucket.org/pygame/pygame/issues/340/surfaceconvert-does-not-remove-the), [issues](https://bitbucket.org/pygame/pygame/issues/341/surfaceset_alpha-sets-the-srcalpha-flag) 
- [x] add a thank you note to website for people who made commits in this release.
- [x] manual testing on linux
- [x] manual testing on mac
- [x] manual testing on windows
- [x] run a few old games you know to see if things work (solar wolf, zanthor, ...).
- [x] prepare the release notes (aka, WHATSNEW).
- [x] skip known pypy failing tests on pypy.
- [x] add python 3.7 builds on 
  - [x] appveyor (windows py3.7 builds)
  - [x] travisci (mac, linux py3.7 builds)
- [x] prepare website news post.
- [x] improve 'contribute' web page.
- [x] release candidate, post to mailing list, give people a week.
- [ ] pre-release wheels, dev builds, release candidates. https://github.com/pygame/pygame/issues/409
- [x] ask for people to test from test.pypi.org
- [x] upload release wheels, and source to pypi.
- [x] upload source release to pygame.org/ftp
- [x] update `downloads.shtml` page on the website with new source release.
- [x] announce on pygame website news section.
- [x] announce on mailing lists (pygame-users, python announce).
- [x] announce on pygame reddit.

**Comment by illume** [comment]
There's a bunch of Debian bugs I've added the [1.9.4 label](https://github.com/pygame/pygame/labels/1.9.4) to. I think these are blocking a release on debian(and derivatives), so should really be fixed before we release.

**Comment by illume** [comment]
I've addressed all the Debian reported issues (fixes, tests, etc,  and replied to their bug tracker). For now, I'll await feedback, and work on other parts of the release.

**Comment by takluyver** [comment]
One thing that it might be worth waiting for: PyPA is in the process of defining a new manylinux standard for binary wheels. This will be based on Centos 6, whereas the current standard is based on Centos 5. Wheels built for the new standard will not be available for quite as many users, but hopefully there will be fewer compatibility issues for the users who can get them. And they should be easier to build.

On the other hand, defining a new standard can take quite a while, so you may not want to wait for that.

**Comment by terencode** [comment]
@illume could you consider #379 for this release? I didn't get any feedback on it.

**Comment by illume** [comment]
When resizing the window with your mouse the height reported in the resize
event is wrong?

**Comment by illume** [comment]
Yeah, that sounds like something for later.

Do you know of any compatibility issues related to the manylinux wheels?
Perhaps I could address them.

Also, perhaps we should add a link to the relevant wiki page on install
error.

**Comment by takluyver** [comment]
I think I already fixed a few compatibility issues by building newer versions of libraries from source for the build environment. Currently, #331 appears to be an issue with the built wheels, but i  don't know where it's coming from, and I suspect that #343 is a compatibility issue as well - I guess that timidity has changed the location of the config file at some point, but I don't know when. If we bundle a version that looks in the new location, that may just introduce a similar a bug for people on systems with the config file in the old location.

**Comment by illume** [comment]
Ok, cool. Thanks for the info, and for fixing those issues! I'll add them
to the list for 1.9.4.

Timidity is unmaintained on Debian for some time it seems. Might be even
worthwhile disabling it.

What I meant by the error messages, was on build failure link to the
Compile pages on the wiki. Eg, on ubuntu link to CompileUbuntu.

**Comment by illume** [comment]
I'm looking into launchpad stuff for the ppa here:
https://code.launchpad.net/~pygame/+recipe/pygame-daily

Which uses the bzr mirror of the github/pygame/pygame repo:
https://code.launchpad.net/~pygame/pygame/main

Looks like the bzr-git plugin they are using was dying on a gpg field in a git commit...
http://launchpadlibrarian.net/347912075/pygame-pygame-main.log
```
2017-12-03 07:35:32 INFO    Starting job.
2017-12-03 07:35:32 INFO    Getting exising bzr branch from central store.
2017-12-03 07:35:33 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2017-12-03 07:35:33 INFO    35 bytes transferred
2017-12-03 07:35:34 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2017-12-03 07:35:37 INFO    Importing branch.
2017-12-03 07:35:42 INFO    Counting objects: 52, done. 0
2017-12-03 07:35:42 INFO    finding revisions to fetch:generating index 0/52
2017-12-03 07:35:42 INFO    finding revisions to fetch:generating index 0/52
2017-12-03 07:35:42 INFO    
Traceback (most recent call last):
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/scripts/code-import-worker.py", line 106, in <module>
    sys.exit(script.main())
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/scripts/code-import-worker.py", line 101, in main
    return import_worker.run()
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/lib/lp/codehosting/codeimport/worker.py", line 617, in run
    return self._doImport()
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/lib/lp/codehosting/codeimport/worker.py", line 820, in _doImport
    inter_branch.fetch(limit=revision_limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/bzrplugins/git/branch.py", line 722, in fetch
    self.fetch_objects(stop_revision, fetch_tags=fetch_tags, limit=limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/bzrplugins/git/branch.py", line 745, in fetch_objects
    determine_wants, self.source.mapping, limit=limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/bzrplugins/git/fetch.py", line 718, in fetch_objects
    limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/bzrplugins/git/fetch.py", line 484, in import_git_objects
    mapping.revision_id_foreign_to_bzr)
  File "/srv/importd.launchpad.net/production/launchpad-rev-18511/bzrplugins/git/mapping.py", line 334, in import_commit
    raise UnknownCommitExtra(commit, [item[0] for item in commit.extra])
bzrlib.plugins.git.errors.UnknownCommitExtra: Unknown extra fields in <Commit 20b1becab2216cb8784088464233e37067601162>: ['gpgsig'].
Import failed:
Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.
```

That cleared up, by clicking the retry button. I guess someone fixed it in the following months.


----

Then I see a missing dependency `musescore-soundfont-gm` for the builds:
- artful https://code.launchpad.net/~pygame/+archive/ubuntu/pygame-dev/+recipebuild/1535314
- bionic https://code.launchpad.net/~pygame/+archive/ubuntu/pygame-dev/+recipebuild/1535315

The xenial build got further along, but there seems to be some version issues in there. https://launchpadlibrarian.net/357778839/buildlog.txt.gz
```
dpkg-genchanges: warning: the current version (1.9.2~pre~ubuntu-r3440+201802201742+42~ubuntu16.04.1) is earlier than the previous one (1.9.2~pre~ubuntu-r3440-1)
```

The packaging files on there need updating it seems.

**Comment by illume** [comment]
Thomas Karl Pietrowski has a PPA for pygame 1.9.3x on python 3 in ubuntu here: https://launchpad.net/~thopiekar

**Comment by illume** [comment]
The docs are building on commits to github.com/pygame/pygame master for the pygame website again. The bitbucket webhook was still happening there. Now there is integration with github instead. Also, a few documentation updates (version number update, https links, work arounds for recent sphinx bugs). Also the launchpad badge is updating properly again.

**Comment by illume** [comment]
Raspberrypi builds binary wheels for itself now with the piwheels project: https://github.com/bennuttall/piwheels/issues/52

**Comment by bennuttall** [comment]
Raspberry Pi wheels for Pygame 1.9.3 are built: https://www.piwheels.hostedpi.com/simple/Pygame/

Assuming the build requirements for 1.9.4 will be the same, these will automatically get built by piwheels when it is released on PyPI.

**Comment by bennuttall** [comment]
Do you send Debian packages to the Raspbian team too?

**Comment by illume** [comment]
Great. I'll have to dust off my boards and give it a go.

We've been trying to get packages up to Debian, which I guess will flow down eventually. 1.9.3 is already packaged by the Debian maintainer. I'm not sure who the Raspbian team is, or how to get in contact with them.

**Comment by bennuttall** [comment]
We can get it into Raspbian quicker than via Debian. Email me ben [at] raspberrypi dot org and I'll introduce you to the Raspbian maintainer.

**Comment by Natureshadow** [comment]
Well, Raspbian is Debian, plus some unnecessarily rebuilt packages qith bad QA. The Debian package will be up to date once 1.9.4 is out.

**Comment by illume** [comment]
There's an issue with the mac travis builds I'm trying to fix. Also pypy on appveyor is now broken because of some internal error. But once these two things are resolved, I'll mark it as a release candidate and ask for testers.

**Comment by hroncok** [comment]
[Fedora issues](https://bugz.fedoraproject.org/pygame) are:

 * doesn't build with 3.7 (this release should fix it)
 * "we may re-enable tests again on ppc64le" (appears to be a downstream only thing now)

So AFAIK you can tick that checkbox.

**Comment by illume** [comment]
Thanks @hroncok :)

I'm trying to push a release this weekend. Last chance for any fixes to go in.

I'm going to mark it RC1 and try and get travis to upload binary wheels for Mac first. I can download the windows files from Appveyor manually, and also do the linux builds manually.

**Comment by illume** [comment]
I would be nice if someone has time to look into these two issues:

- https://github.com/pygame/pygame/issues/455
- https://github.com/pygame/pygame/issues/456

**Comment by illume** [comment]
I setup python 3.7 builds on mac/win/linux with travis and appveyor, but it's failing on windows. So getting into debugging this now.

**Comment by illume** [comment]
The website news post, and mailing post will be the same as the draft on the releases page. https://github.com/pygame/pygame/releases/tag/untagged-378fa95601556f13fbec

**Comment by illume** [comment]
Whilst github is broken, working on this 'pre release build' thingo. https://github.com/pygame/pygame/issues/409

Will also work on the 'contribute' page... add something about how to do a unit test, and link to the 'easy git issues', and put the 'awesome pygame' stuff somewhere on the website.

**Comment by illume** [comment]
Got portmidi working on travis mac builders with the Formula here: https://github.com/pygame/homebrew-portmidi and used that in here: https://github.com/pygame/pygame/pull/467

Then, the upload to pypi seemed to work. Sent a message out asking for people to test the mac builds (like previously done with windows builds). Will do the manylinux wheels next.

Had to drop python 3.4 from the travis builds... because they don't have that on xenial it seems (but that supports 3.7). Doing python3.6 builds on travis will be some sort of torture, so not doing that (I've had enough CI torture for now).

**Comment by illume** [comment]
There is a scrap issue reported by Ian on the mailing list.
```
======================================================================
ERROR: test_scrap_put_text (pygame.tests.scrap_test.ScrapModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\dev\Python37\lib\site-packages\pygame\tests\scrap_test.py", line 133,
 in test_scrap_put_text
    scrap.put (pygame.SCRAP_TEXT, as_bytes("Another String"))
pygame.error: content could not be placed in clipboard.
```

**Comment by illume** [comment]
There's some errors reported here by ntoll. https://gist.github.com/ntoll/893b3a58f21a48ef0cc94f1d58f80654 I think they are related to the virtual machine not having a sound device. The syntax error is odd... and I can't reproduce it. Perhaps something to do with when tests fail like that on python 3.7.

**Comment by takluyver** [comment]
It looks like the test runner code is trying to `eval` some output which is meant to be a Python dictionary, but now includes a warning message as well.

**Comment by illume** [comment]
Ah ok. Right. Thanks for looking into that. 

I got travis building a mac python 3.6 wheel. https://github.com/pygame/pygame/pull/470

**Comment by illume** [comment]
The release candidate [1.9.4rc1](https://github.com/pygame/pygame/releases/tag/1.9.4rc1) has been uploaded to pypi. Real release in a couple of hours.

**Comment by illume** [comment]
It's done. https://github.com/pygame/pygame/releases/tag/1.9.4

**Comment by illume** [comment]
As well, I added announcing on https://discourse.libsdl.org/, ldjam.com, and raspberrypi.org to the release checklist.

**Comment by bennuttall** [comment]
https://twitter.com/ben_nuttall/status/1025138039541170182
