### ISSUE TITLE
pygame 1.9.5 release

### ISSUE THREAD

**Issue by illume** [pygame/pygame#495]
This is a checklist of things to do before the new release.

Note: what goes in 1.9.5 is still being decided and planned.
This will still be using SDL 1.2.

## required issues to be complete before release.

- [x] deploy wheels to github release from travis/appveyor.
- [x] Mac 10.4 black screen (requires a SDL fix). https://github.com/pygame/pygame/issues/555
- [x] unclean tarball fix for Debian https://github.com/pygame/pygame/issues/543

---

## Nice to have issues fixed.

- [ ] ~~high cpu sound issue~~ issue identified, reported upstream https://github.com/pygame/pygame/issues/331
- [ ] timidity config paths issue https://github.com/pygame/pygame/issues/343
- [ ] ~~ move towards using new SDL 1.2 release. https://github.com/pygame/pygame/issues/497 ~~
- [ ] FreeBSD fixes https://github.com/pygame/pygame/issues/473
- [ ] ~~ update manylinux build to use SDL 1.2.16 branch. https://github.com/pygame/pygame/issues/562 ~~
- [ ] ~~ update homebrew builds to use SDL 1.2.16 branch. ~~

---

## Checklist of things to do when required issues are complete.

- [x] go through the issue tracker, and pull requests to include as much as we can.
- [x] announce intention to release on mailing list.
- [ ] look at [distro bug trackers](http://www.pygame.org/wiki/patchesandbugs#OS/Distribution%20bug%20trackers%20for%20pygame) for bugs, and patches (debian, fedora, etc).
  - [ ] address debian issues
  - [ ] look through ubuntu issues
  - [ ] [fedora issues](https://bugz.fedoraproject.org/pygame)
- [x] docs are building and ok.
- [x] manual testing on linux
- [x] manual testing on mac
- [x] manual testing on windows
- [x] run a few old games you know to see if things work (solar wolf, zanthor, ...).
- [x] prepare the release notes (in the release draft). https://github.com/pygame/pygame/issues/561
- [x] skip known pypy failing tests on pypy.
- [x] prepare website news post.
- [x] improve 'contribute' web page.
- [x] release candidate, post to mailing list, give people a week.
- [x] pre-release wheels, dev builds, release candidates. https://github.com/pygame/pygame/issues/409
- [x] upload release wheels, and source to pypi.
- [x] upload source release to pygame.org/ftp
- [x] update `downloads.shtml` page on the website with new source release.
- [x] announce on pygame website news section.
- [x] announce on mailing lists (pygame-users, python announce).
- [x] announce on pygame reddit.
- [x] announce on pygame twitter.
- [x] announce on https://discourse.libsdl.org/
- [x] announce on https://ldjam.com/
- [x] announce on https://www.raspberrypi.org forum

**Comment by Natureshadow** [comment]
Please look into #587 for the release, should be trivial (if skipping the tests is an option or fixing them is easy).

**Comment by illume** [comment]
Rather than try and get SDL 1.2.16 released (hard), it's probably better for pygame to concentrate on SDL2 at this point. It would be good for the community if another SDL1 was released, but realistically I can't do that, and just hoping that magically happens isn't a good idea. The amount of testing of a not-released SDL 1.2.16 is probably as much as finishing our remaining SDL2 issues.

So, I'm going to aim to do a pygame 1.9.5 release as soon as possible. So I've removed those other tasks, leaving just the Debian and Mac ones. I'll use a similar technique that I implemented in stuntcat of getting github/travis/appveyor to upload the binaries to a draft 'github release' when making a tag. This can then be used for testing the pygame 2/SDL2 development releases.

**Comment by illume** [comment]
I got the github/appveyor pushing wheels to a draft github release:
https://github.com/pygame/pygame/pull/924

**Comment by illume** [comment]
pypy isn't compiling issue: https://github.com/pygame/pygame/issues/925

**Comment by illume** [comment]
dlon fixed the pypy issue, and a few other PRs were merged in.

I pushed the 1.9.5.rc1 tag.

**Comment by illume** [comment]
The various distribution files have been uploaded now. 

https://github.com/pygame/pygame/releases/tag/1.9.5.rc1
https://pypi.org/project/pygame/1.9.5rc1/#files

`python -m pip install pygame==1.9.5.rc1 --pre`

**Comment by illume** [comment]
I noticed there are no python 3.4 and 3.5, but I guess that should not hold up a release.

**Comment by notpygame** [comment]
https://github.com/pygame/pygame/releases/tag/1.9.5.rc2

**Comment by illume** [comment]
I tagged 1.9.5.
