### ISSUE TITLE
Improvements to pygame.draw

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#896]
Here are some improvements that can be made to `pygame.draw` related areas.

Note: There are currently 2 draw modules `draw` (`src_c/draw.c`) and `draw_py` (`src_py/draw_py.py`). Any changes/tests should be applied to both modules.

- [x] Add keyword arguments to the draw functions (related to issue #808). Also add relevant tests and update the documentation with [sphinx info field lists](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists) for the parameters and return values.
  - [x] `pygame.draw.rect`
  - [x] `pygame.draw.polygon`
  - [x] `pygame.draw.circle`
  - [x] `pygame.draw.ellipse`
  - [x] `pygame.draw.arc`
  - [x] `pygame.draw.line`
  - [x] `pygame.draw.lines`
  - [x] `pygame.draw.aaline`
  - [x] `pygame.draw.aalines`

- [ ] Add tests to ensure correct bounding rects are being returned from all the draw functions. In some instances the bounding rects for `pygame.draw.line` and `pygame.draw.aaline` are incorrect (issue #895). Other draw functions could have similar issues.
  - [ ] `pygame.draw.rect` (related to issue #1305)
  - [ ] `pygame.draw.polygon` (related to issue #1306)
  - [x] `pygame.draw.circle` (related to issue #1122)
  - [x] `pygame.draw.ellipse` (related to issue #1241)
  - [ ] `pygame.draw.arc` (being tracked by issue #1143, related to issue #1212)
  - [x] `pygame.draw.line` (related to issue #895)
  - [x] `pygame.draw.lines` (related to issue #1117)
  - [x] `pygame.draw.aaline` (related to issue #895)
  - [x] `pygame.draw.aalines` (related to issue #1153)

- [x] Add tests to ensure all the draw functions respect a given surface's clip area.
  - [x] `pygame.draw.rect`
  - [x] `pygame.draw.polygon`
  - [x] `pygame.draw.circle`
  - [x] `pygame.draw.ellipse`
  - [x] `pygame.draw.arc`
  - [x] `pygame.draw.line`
  - [x] `pygame.draw.lines`
  - [x] `pygame.draw.aaline`
  - [x] `pygame.draw.aalines`

- [x] Update the `pygame.draw` documentation. Some items of note.
  - [x] Ensure proper code linking and highlighting.
  - [x] Add a link to `pygame.gfxdraw` as an alternative to `pygame.draw`.
  - [x] Add info on what happens when `pygame.draw.line`/`pygame.draw.lines` is given a `width=0`.
  - [x] Add info on what the returned bounding rect value is when the requested draw shape is fully outside of the draw surface's bounds/clip area.
  - [x] Clarify the bounding rectangle definition to state that the 'minimum' bounding area/rectangle is returned.
